package com.stkj.supermarketmini.base.greendao.generate;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.stkj.supermarketmini.payment.model.WaitHistoryOrderInfo;

import com.stkj.supermarketmini.base.greendao.generate.WaitHistoryOrderInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig waitHistoryOrderInfoDaoConfig;

    private final WaitHistoryOrderInfoDao waitHistoryOrderInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        waitHistoryOrderInfoDaoConfig = daoConfigMap.get(WaitHistoryOrderInfoDao.class).clone();
        waitHistoryOrderInfoDaoConfig.initIdentityScope(type);

        waitHistoryOrderInfoDao = new WaitHistoryOrderInfoDao(waitHistoryOrderInfoDaoConfig, this);

        registerDao(WaitHistoryOrderInfo.class, waitHistoryOrderInfoDao);
    }
    
    public void clear() {
        waitHistoryOrderInfoDaoConfig.clearIdentityScope();
    }

    public WaitHistoryOrderInfoDao getWaitHistoryOrderInfoDao() {
        return waitHistoryOrderInfoDao;
    }

}
