package com.stkj.cashier.greendao;


import com.stkj.cashier.setting.model.db.CompanyMemberdbEntity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig companyMemberdbEntityDaoConfig;

    private final CompanyMemberdbEntityDao companyMemberdbEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        companyMemberdbEntityDaoConfig = daoConfigMap.get(CompanyMemberdbEntityDao.class).clone();
        companyMemberdbEntityDaoConfig.initIdentityScope(type);

        companyMemberdbEntityDao = new CompanyMemberdbEntityDao(companyMemberdbEntityDaoConfig, this);

        registerDao(CompanyMemberdbEntity.class, companyMemberdbEntityDao);
    }
    
    public void clear() {
        companyMemberdbEntityDaoConfig.clearIdentityScope();
    }

    public CompanyMemberdbEntityDao getCompanyMemberdbEntityDao() {
        return companyMemberdbEntityDao;
    }

}
