package com.stkj.supermarket.base.greendao.generate;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.stkj.supermarket.pay.model.PayHistoryOrderInfo;
import com.stkj.supermarket.pay.model.WaitHistoryOrderInfo;
import com.stkj.supermarket.setting.model.FacePassPeopleInfo;

import com.stkj.supermarket.base.greendao.generate.PayHistoryOrderInfoDao;
import com.stkj.supermarket.base.greendao.generate.WaitHistoryOrderInfoDao;
import com.stkj.supermarket.base.greendao.generate.FacePassPeopleInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig payHistoryOrderInfoDaoConfig;
    private final DaoConfig waitHistoryOrderInfoDaoConfig;
    private final DaoConfig facePassPeopleInfoDaoConfig;

    private final PayHistoryOrderInfoDao payHistoryOrderInfoDao;
    private final WaitHistoryOrderInfoDao waitHistoryOrderInfoDao;
    private final FacePassPeopleInfoDao facePassPeopleInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        payHistoryOrderInfoDaoConfig = daoConfigMap.get(PayHistoryOrderInfoDao.class).clone();
        payHistoryOrderInfoDaoConfig.initIdentityScope(type);

        waitHistoryOrderInfoDaoConfig = daoConfigMap.get(WaitHistoryOrderInfoDao.class).clone();
        waitHistoryOrderInfoDaoConfig.initIdentityScope(type);

        facePassPeopleInfoDaoConfig = daoConfigMap.get(FacePassPeopleInfoDao.class).clone();
        facePassPeopleInfoDaoConfig.initIdentityScope(type);

        payHistoryOrderInfoDao = new PayHistoryOrderInfoDao(payHistoryOrderInfoDaoConfig, this);
        waitHistoryOrderInfoDao = new WaitHistoryOrderInfoDao(waitHistoryOrderInfoDaoConfig, this);
        facePassPeopleInfoDao = new FacePassPeopleInfoDao(facePassPeopleInfoDaoConfig, this);

        registerDao(PayHistoryOrderInfo.class, payHistoryOrderInfoDao);
        registerDao(WaitHistoryOrderInfo.class, waitHistoryOrderInfoDao);
        registerDao(FacePassPeopleInfo.class, facePassPeopleInfoDao);
    }
    
    public void clear() {
        payHistoryOrderInfoDaoConfig.clearIdentityScope();
        waitHistoryOrderInfoDaoConfig.clearIdentityScope();
        facePassPeopleInfoDaoConfig.clearIdentityScope();
    }

    public PayHistoryOrderInfoDao getPayHistoryOrderInfoDao() {
        return payHistoryOrderInfoDao;
    }

    public WaitHistoryOrderInfoDao getWaitHistoryOrderInfoDao() {
        return waitHistoryOrderInfoDao;
    }

    public FacePassPeopleInfoDao getFacePassPeopleInfoDao() {
        return facePassPeopleInfoDao;
    }

}
