package com.stkj.infocollect.base.greendao.generate;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.stkj.infocollect.setting.model.FacePassPeopleInfo;

import com.stkj.infocollect.base.greendao.generate.FacePassPeopleInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig facePassPeopleInfoDaoConfig;

    private final FacePassPeopleInfoDao facePassPeopleInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        facePassPeopleInfoDaoConfig = daoConfigMap.get(FacePassPeopleInfoDao.class).clone();
        facePassPeopleInfoDaoConfig.initIdentityScope(type);

        facePassPeopleInfoDao = new FacePassPeopleInfoDao(facePassPeopleInfoDaoConfig, this);

        registerDao(FacePassPeopleInfo.class, facePassPeopleInfoDao);
    }
    
    public void clear() {
        facePassPeopleInfoDaoConfig.clearIdentityScope();
    }

    public FacePassPeopleInfoDao getFacePassPeopleInfoDao() {
        return facePassPeopleInfoDao;
    }

}
